SET FOREIGN_KEY_CHECKS=0
DROP TABLE EVENTDAY_TICKET
DROP TABLE COMPANY
DROP TABLE VENUE
DROP TABLE EVENT
DROP TABLE SEAT
DROP TABLE TICKET
DROP TABLE EVENTDAY
DROP TABLE RESERVATION
DROP TABLE COMPANY_ALLOWEDEVENTTYPES
DROP TABLE SEQUENCE